networks:
  my-network:
    driver: bridge

services:
  discovery-service:
    image: ghcr.io/leang302/discovery-service:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - my-network
    restart: unless-stopped

  config-server:
    image: ghcr.io/leang302/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - my-network
    restart: unless-stopped
    depends_on:
      - discovery-service

  # Product DB
  product-db:
    image: postgres:15
    container_name: product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - my-network
    restart: unless-stopped

  # User DB
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - my-network
    restart: unless-stopped

  # Category DB
  category-db:
    image: postgres:15
    container_name: category-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: categorydb
    ports:
      - "5434:5432"
    volumes:
      - category-db-data:/var/lib/postgresql/data
    networks:
      - my-network
    restart: unless-stopped

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: user-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: userdb
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HTTP_ENABLED: true
    ports:
      - "8080:8080"
    depends_on:
      - user-db
    networks:
      - my-network
    restart: unless-stopped

volumes:
  product-db-data:
  user-db-data:
  category-db-data:
